version: '3.8'

services:
  structurizr:
    image: structurizr/cli:latest
    pull_policy: always
    command: export -w workspace.dsl -format plantuml/structurizr -output generated
    volumes:
      - ./physio_connect_c4:/usr/local/structurizr/
  context-mapper:
    image: culmi/context-mapper-cli:6.7.0
    pull_policy: always
    entrypoint: ./context-mapper-cli-6.7.0/bin/cm generate -i /usr/local/mapper/domain_model/domain.cml -g plantuml -o /usr/local/mapper/arc42_documentation/domain_model
    volumes: 
      - ./:/usr/local/mapper/
  copyer:
    image: alpine
    pull_policy: always
    command: cp -ru /usr/local/copyer/physio_connect_c4/generated/ /usr/local/copyer/arc42_documentation/structurizr_diagrams
    depends_on:
      structurizr:
        condition: service_completed_successfully
    volumes:
      - ./:/usr/local/copyer/
  asciidoctor:
    image: culmi/asciidoctor-with-prawn-gmagick:latest
    pull_policy: always
    depends_on:
      copyer:
        condition: service_completed_successfully
      context-mapper:
        condition: service_completed_successfully
    command: asciidoctor -b pdf -r asciidoctor-diagram -r asciidoctor-pdf -a pdf-theme=main -a pdf-themesdir=themes arc42-template.adoc
    volumes:
      - ./arc42_documentation:/documents/
