version: '3.8'

services:
  structurizr:
    image: structurizr/cli:latest
    pull_policy: always
    command: export -w workspace.dsl -format plantuml/structurizr -output generated
    volumes:
      - ./physio_connect_c4:/usr/local/structurizr/
  copyer:
    image: alpine
    pull_policy: always
    command: cp -ru /usr/local/copyer/physio_connect_c4/generated/ /usr/local/copyer/arc42_documentation/structurizr_diagrams
    depends_on:
      structurizr:
        condition: service_completed_successfully
    volumes:
      - ./:/usr/local/copyer/
  asciidoctor:
    image: asciidoctor/docker-asciidoctor:latest
    pull_policy: always
    depends_on:
      copyer:
        condition: service_completed_successfully
    command: asciidoctor -b pdf -r asciidoctor-diagram -r asciidoctor-pdf arc42-template.adoc
    volumes:
      - ./arc42_documentation:/documents/
