version: '3.8'

services:
  structurizr:
    image: structurizr/cli:latest
    command: export -w template.dsl -format plantuml/structurizr -output generated
    volumes:
      - ./c4_diagrams:/usr/local/structurizr/
  asciidoctor:
    image: asciidoctor/docker-asciidoctor:latest
    depends_on:
      structurizr:
        condition: service_completed_successfully
    command: asciidoctor -b pdf -r asciidoctor-diagram -r asciidoctor-pdf arc42-template.adoc
    volumes:
      - ./arc42_documentation:/documents/
