@startuml test diagram
title Domain Model Version 1
Entity Therapie {
    Status
}
Entity Session
Entity Übung {
    Startzeit
    Endzeit
}
Entity Patient {
    AHVNummer
}

Class ÜbungsDefinition
Class Beschreibung
Class Therapeut


Therapie --* Session

Session --* Übung

Therapie --o Patient

Session --o Patient

Übung --o Patient

Übung --o "1" ÜbungsDefinition

ÜbungsDefinition --o Beschreibung

Therapie --o Therapeut

@enduml