[#solution-strategy]
== Lösungsstrategie

Dieses Kapitel repräsentiert eine Zusammenfassung der fundamentalen Lösungsansätze, Entwurfsentscheidungen und Prinzipien, welche als grundlegender Treiber für den Aufbau und die Evolution der Systemarchitektur von Physio Connect gelten.

[#architecture-principles]
=== Architekturprinzipien

Die folgenden Prinzipien müssen bestmöglich während dem Design und der Umsetzung von Physio Connect eingehalten werden.

[options="header",cols="1,3,6"]
|===
|ID|Name|Beschreibung

|AP-1
|Open Source bevorzugen und unterstützen
|Falls möglich sollen Open Source-Lösungen für Libraries, Komponenten, Systeme und Tools verwendet werden. Falls eine Open Source-Lösung eine gewünschte Funktionalität nicht unterstützt, soll in Betracht gezogen werden, diese Funktionalität direkt im Open Source-Projekt zu implementieren.

|AP-2
|"Buy before make"
|Falls für eine Problemstellung keine Open Source- (siehe AP-1) sondern lediglich eine kostenpflichtige Lösung existiert, sollte zuerst eingeschätzt werden, wie das Verhältnis zwischen (Lizenz-)Kosten und alternativem Aufwand / Komplexität im Falle einer eigenen Implementation aussieht. Spricht das Verhältnis eher für die kostenpflichtige Lösung, soll diese erworben werden bevor wir eine äquivalente Lösungsvariante selbst implementieren. Dieses Prinzip dient unter Anderem dazu, eine kurze Markteinführungszeit (Time-to-Market) zu erreichen.

|AP-3
|Skalierbarkeit
|Alle Container, deren Ressourcenverbrauch stark mit der Anzahl aktiver Benutzer korreliert, müssen horizontal skalierbar und zustandslos (stateless) sein. Container, deren Ressourcenverbrauch *nicht* oder nur minimal mit der Anzahl aktiver Benutzer korreliert, müssen nicht optimal skalierbar aufgebaut werden.

|AP-4
|Protokolle 
|Wenn immer möglich sollen standardisierte, etablierte und sichere Protokolle verwendet werden. Sicherheit ist höher zu gewichten als Overhead und Geschwindigkeit.

|AP-5
|Programmiersprachen
|Verwendete Programmiersprachen müssen plattformunabhängig, etabliert und wenn möglich statisch typisiert (= zur Kompilierzeit) sein. Zusätzlich sollen bereits im Projekt verwendete Sprachen präferiert werden, um den Technologiestack klein und einfach zu halten.

|AP-6
|Cloud Native
|Alle umzusetzenden Komponenten sollen dem https://aws.amazon.com/what-is/cloud-native/[Cloud Native-Prinzip] entsprechen und in einem lokalen Kubernetes-Cluster ausführbar sein. Clusterweite Standards für Logging, Überwachbarkeit (Monitoring) und Sicherheit müssen eingehalten werden.

|AP-7
|Everything as Code (EaC), Versionierung 
|Alle Artefakte, welche intern oder extern ausgeliefert werden, sollen - sofern technisch möglich - als Code existieren und unter Git versioniert sein. Dazu zählen Quellcode, Softwarearchitekturdokumente, Analysen, Entscheidungen, Geschäftsprozesse, Endbenutzerdokumentationen, Protokolle von Meetings usw. +
Ausgeschlossen sind Wegwerfzeichnungen, Diskussionen, aufgezeichnete Meetings usw.

|AP-8
|Gemeinsame Codebasis für alle unterstützten Plattformen
|Es soll eine gemeinsame Codebasis existieren, welche alle unterstützten Plattformen abdeckt. Falls Apps für verschiedene Devices benötigt werden, muss dies mit einer Codebasis gelöst werden.

|AP-9
|Verwendete Datenformate
a|
Die folgende Priorität soll bezüglich der Verwendung von Datenformaten eingehalten werden:

1. etablierte, standardisierte Datenformate
2. Drittanbieter-Datenformate
3. selbsterstellte Datenformate

|AP-10
|Security: Umsetzung einer strikten Zugriffskontrolle
|Grundsätzlich sollen bei den verwendeten Sicherheitskonzepten jeweils alle Zugriffe verboten werden ("deny all") und nur Benutzer mit expliziter Erlaubnis sollen System- und Datenzugriff erhalten bzw. spezifische Aktionen ausführen dürfen. Dies gilt sowohl für Netzwerkkomponenten wie Firewalls als auch für Code-Level Autorisierungen bei API Requests (zu berücksichtigen bei "User to Service"- sowie "Service to Service"-Requests).

|AP-11
|Security: Einhaltung von aktuell geltenden Security-Standards
|Aufgrund der Übermittlung, Verarbeitung und Ablage persönlicher Gesundheitsdaten muss zwingend sichergestellt sein, dass alle beteiligten (Sofware-)Systeme und Komponenten die aktuellsten Sicherheitsstandards erfüllen, welche für den einwandfreien Umgang mit persönlichen Gesundheitsdaten relevant sind. Dies betrifft insbesondere den Schutz vor unbefugtem System- und Datenzugriff (siehe AP-10) und die Anwendung von aktuell empfohlenen Handshake-, Verschlüsselungs- / Hashing- und Ablageverfahren (inkl. korrekter Anonymisierung der Daten bei potenzieller Weitergabe).

|AP-12
|Continuous Integration & Delivery
|Alle Systeme müssen so umgesetzt werden, dass sie nach einer Änderung des Quellcodes automatisiert über eine CI/CD-Pipeline verifiziert (Build, Test) und deployed werden können.

|===

===  Lösungsansätze für die Erreichung der Qualitätsziele

Die nachfolgende Tabelle visualisiert eine Gegenüberstellung zwischen den zentralen <<#quality-goals,Qualitätszielen>> der Physio Connect-Systemarchitektur und den Lösungsansätzen, welche massgeblich zu der Erreichung dieser Ziele beitragen. Die Lösungsansätze können sich dabei aus einer Kombination von <<#architecture-decisions,Entscheidungen>>, <<#concepts,Konzepten>>, <<#architecture-principles,Prinzipien>>, <<#architecture-tactics,Taktiken>> und sonstigen Ideen zusammensetzen.

[options="header",cols="2,2,6"]
|===
|Qualitätsziel (ID)|Beschreibung|Lösungsansätze

|Interoperability +
(QG-1)
a|
Kompatibilität mit Umsystemen:

* Patienten-App
* Übungskatalog
* Benutzerverwaltung
* Dokumentationssystem +
(Erweiterung)

a|
Entscheidungen:

* ADR-BAC-50 +
Die APIs externer Umsysteme wie __Übungskatalog__ und __Benutzerverwaltung__ werden in dedizierten Wrapper Services gekapselt. Dadurch lässt sich die Interoperabilität mit diesen Umsystemen an einem zentralen Ort sicherstellen.

Prinzipien:

* AP-4 +
Verwendung von etablierten, standardisierten (Kommunikations-)Protokollen
* AP-9 +
Verwendung von etablierten, standardisierten Datenformaten

Taktiken:

* TA-IOP-1 +
Jede bereitgestellte Schnittstelle (z.B. API Endpoint) muss formal prüfen, ob eingehende Daten den definierten Datentypen entsprechen. Ist dem nicht der Fall, müssen standardisierte Response Codes zurückgegeben werden.
* TA-IOP-2 +
Bei Requests, welche intern an weitere Komponenten oder (externe) Umsysteme weitergeleitet werden, soll das Antwortverhalten einem klar definierten Schema folgen.

|Confidentiality +
(QG-2)
|Einhaltung bestehender Datenschutzverordnungen und -gesetze im Umgang mit persönlichen Gesundheitsdaten
a|
Entscheidungen:

* ADR-SEC-10 +
Die systemweite Authentifizierung wird mit etablierten Technologien (OAuth 2.0 & OpenID Connect, Multi-factor authentication) sichergestellt. Der dabei verwaltende Identity Provider (https://www.keycloak.org/[Keycloak]) ist Bestandteil des Umsystems __Benutzerverwaltung__.
* ADR-SEC-11 +
Mittels der Unterstützung bekannter Social Identity Provider kann auf die redundante Datenhaltung von Passwörtern verzichtet werden.
* ADR-BAC-40 +
Die Backend-interne Kommunikation verläuft über verschlüsselte HTTPS-Verbindungen (SSL / TLS).

Prinzipien:

* AP-4 +
Einsatz von standardisierte, etablierte und sichere Protokollen
* AP-10 +
Security: Umsetzung einer strikten Zugriffskontrolle
* AP-11 +
Security: Einhaltung von aktuell geltenden Security-Standards

Taktiken:

* TA-CNF-1 +
Verschlüsselte Kommunikation zwischen allen Systemkomponenten
* TA-CNF-2 +
Authentifizierungs- und Autorisierungsmechanismen für jeden eingehenden Request
* TA-CNF-3 +
Sicherheitsrichtlinien bei der Implementation neuer API Endpoints

|Confidentiality +
(QG-2) +
(Platzbedingte Fortsetzung)
|Einhaltung bestehender Datenschutzverordnungen und -gesetze im Umgang mit persönlichen Gesundheitsdaten
a|
Sonstige Punkte:

* Die systemweite Autorisierung (Zuweisung und Prüfung der Benutzerrollen und -Berechtigungen) verläuft über das Umsystem __Benutzerverwaltung__.
* Durch die Verwendung eines Load Balancer / Reverse Proxy (siehe <<#building-block-view,Bausteinsicht>>) wird ein zentraler, öffentlicher Einstiegspunkt bereitgestellt, durch welchen alle eingehenden Requests "geschleust" werden. Dies reduziert die allgemeine Angriffsfläche, da die restlichen Systemkomponenten innerhalb eines virtuellen Netzwerks betrieben werden können, welches nicht öffentlich zugänglich ist.

|Modifiability +
(QG-3)
|Flexible Modifizier- und Erweiterbarkeit für existierende und zukünftige Schnittstellen
a|
Entscheidungen:

* ADR-BAC-10 +
Das Backend wird in unabhängige, einfach modifizier- und erweiterbare Microservices aufgeteilt.
* ADR-BAC-20 +
Die interne Struktur der Backend Services befolgt das Design Pattern der hexagonalen Architektur (Ports & Adapters).
* ADR-BAC-50 +
Die APIs externer Umsysteme wie __Übungskatalog__ und __Benutzerverwaltung__ werden in dedizierten Wrapper Services gekapselt. 

Konzepte:

* Hexagonale Architektur (Ports & Adapters)

Taktiken:

* TA-MOD-1 +
Bei Modifikationen und Erweiterungen müssen bestimmte Implementationsrichtlinien berücksichtigt werden, um stets eine optimale Modifizier- und Erweiterbarkeit aller Systemkomponenten zu gewährleisten.
* TA-MOD-2 +
Auf Änderungen der APIs externer Umsysteme kann aufgrund der Verwendung von dedizierten Wrapper Services schnell reagiert werden. 

|===

Des Weiteren stellen die folgenden Qualitätsattribute ebenfalls wichtige Entscheidungsgrundlagen dar:

[options="header",cols="2,2,6"]
|===
|Qualitätsattribut|Beschreibung|Lösungsansätze

|Time behaviour
|Möglichst effiziente Verarbeitung der eingehenden Messdaten +
(siehe <<#scenarios-time-behaviour,Qualitätsszenario __SZ-TIB-1__>>)
a|
Entscheidungen:

* ADR-BAC-10 +
Das Backend wird in unabhängige Microservices aufgeteilt, welche bei Bedarf gut skalierbar sind.
* ADR-BAC-30 +
Die Verteilung der Datenmengen auf mehrere Datenbanken (sprich in diesem Falle eine separate Datenbank für die Messdaten) kann die Leistung und Skalierbarkeit des Gesamtsystems verbessern.
* ADR-BAC-31 +
Dokumentdatenbanken lassen sich bei Bedarf (in der Regel) einfacher skalieren als relationale Datenbanken.
* ADR-BAC-50 +
Die APIs externer Umsysteme wie __Übungskatalog__ und __Benutzerverwaltung__ werden in dedizierten Wrapper Services gekapselt, welche ebenfalls gut skalierbar sind.
* ADR-HST-10 +
Das standardmässige Hosting von Physio Connect in der Cloud ermöglicht eine effiziente vertikale / horizontale Skalierung.

Prinzipien:

* AP-3 +
Komponenten, deren Ressourcenverbrauch stark mit der Anzahl aktiver Benutzer korreliert, müssen horizontal skalierbar und zustandslos (stateless) sein.
* AP-9 +
Verwendung von etablierten, standardisierten Datenformaten, welche laufend hinsichtlich ihres Ressourcenverbrauchs optimiert werden.

Sonstige Punkte:

* Durch die Verwendung eines Load Balancer / Reverse Proxy (siehe <<#building-block-view,Bausteinsicht>>) können statische Inhalte temporär gecached werden, was die Response-Zeiten reduziert.

|Capacity
|Parallele Verwendung von Physio Connect durch mehrere Benutzer +
(siehe <<#scenarios-capacity,Qualitätsszenario __SZ-CAP-1__>>)
a|
Entscheidungen:

* ADR-BAC-10 +
Das Backend wird in unabhängige Microservices aufgeteilt, welche bei Bedarf gut skalierbar sind.
* ADR-BAC-30 +
Die Verteilung der Datenmengen auf mehrere Datenbanken (sprich in diesem Falle eine separate Datenbank für die Messdaten) kann die Leistung und Skalierbarkeit des Gesamtsystems verbessern.
* ADR-BAC-31 +
Dokumentdatenbanken lassen sich bei Bedarf (in der Regel) einfacher skalieren als relationale Datenbanken.
* ADR-BAC-50 +
Die APIs externer Umsysteme wie __Übungskatalog__ und __Benutzerverwaltung__ werden in dedizierten Wrapper Services gekapselt, welche ebenfalls gut skalierbar sind.
* ADR-HST-10 +
Das standardmässige Hosting von Physio Connect in der Cloud ermöglicht eine effiziente vertikale / horizontale Skalierung.

Prinzipien:

* AP-3 +
Komponenten, deren Ressourcenverbrauch stark mit der Anzahl aktiver Benutzer korreliert, müssen horizontal skalierbar und zustandslos (stateless) sein.

|Fault tolerance
|Resilientes Verhalten bei einem Ausfall oder fehlerhaften Antworten der Umsysteme +
(siehe <<#scenarios-fault-tolerance,Qualitätsszenarien __SZ-FLT-1__, __SZ-FLT-2__>>)
a|
Entscheidungen:

* ADR-BAC-50 +
Die APIs externer Umsysteme wie __Übungskatalog__ und __Benutzerverwaltung__ werden in dedizierten Wrapper Services gekapselt, welche möglichst resilient implementiert sind (z.B. Verwendung von Retry Policies), sodass Physio Connect bei einem Ausfall oder fehlerhaften Verhalten der Umsysteme zumindest noch eingeschränkt verwendet werden kann.

Taktiken:

* TA-IOP-2 +
Bei Requests, welche intern an weitere Komponenten oder (externe) Umsysteme weitergeleitet werden, soll das Verhalten bei Timeouts oder auftretenden Fehlern einem klar definierten Schema folgen.

|Installability
|Flexible Konfigurierbarkeit ermöglicht Installation und Betrieb in unterschiedlichen Umgebungen +
(siehe <<#scenarios-installability,Qualitätsszenario __SZ-INT-1__>>)
a|
Entscheidungen:

* ADR-HST-10 +
Das standardmässige Hosting von Physio Connect ist bei einem Cloud-Provider vorgesehen. Beim Design und der Implementation soll jedoch darauf geachtet werden, dass ein potenzielles on-premises-Hosting (beispielsweise durch eine hohe Konfigurierbarkeit) ebenfalls möglich ist.

Prinzipien:

* AP-6 +
Durch die Anwendung des Cloud Native-Prinzips besitzt Physio Connect bereits ein grundlegendes Mass an Portabilität, da das System in unterschiedlichen Cloud-Umgebungen "installiert" und betrieben werden kann. Durch den Einsatz von https://www.docker.com/resources/what-container/[Containern] (z.B. Docker), welche grundsätzlich plattformunabhängig funktionieren, lässt sich dieser Effekt auch auf on-premises-Umgebungen replizieren.

|===
