[[section-deployment-view]]
== Verteilungssicht

Dieses Kapitel bietet eine detaillierte Beschreibung der technischen Infrastruktur, welche für das Deployment und den Betrieb von Physio Connect verwendet wird. Zudem wird definiert, wie die fundamentalen link:05_building_block_view.adoc#section-building-block-view[Software-Bausteine / -Komponenten] des Systems auf die eingesetzte Infrastruktur abgebildet werden.

=== Infrastruktur mit einer Physio Connect-Instanz

==== Cloud Hyperscaler

**Motivation**

Gemäss den link:09_architecture_decisions.adoc#section-design-decisions[Architekturentscheidungen] *ADR-HST-10* und *ADR-HST-11* wurde bestimmt, dass nur eine globale Instanz des Physio Connect-Systems produktiv eingesetzt werden soll, welche von uns gehosted wird.

Um eine skalierbare Umgebung umzusetzen, welche ohne hohe Initialkosten in Betrieb genommen und kosteneffizient betrieben werden kann, wurde gemäss *ADR-HST-10* entschieden, einen Cloud Hyperscaler zu verwenden. Zu diesem Zeitpunkt ist noch unbekannt, welcher Hyperscaler verwendet werden soll.

**Qualitäts- und Performance-Eigenschaften**

Um sicherzustellen, dass keine Ressourcen die Schweizer Grenzen verlassen, dürfen nur Ressourcen des Hyperscalers verwendet werden, welche sich in einer Schweizer Region befinden.

Der Kubernetes Cluster soll zu jeder Zeit mindestens eine https://komodor.com/learn/kubernetes-nodes-complete-guide/[Master Node und zwei Worker Nodes] besitzen, um die Ausfallsicherheit zu gewährleisten.

Die Kapazität des Clusters soll in der Nacht jeweils auf ein Minimum reduziert werden.

Die Anzahl Replikationen der Pods soll automatisch gemäss Ressourcenverbrauch skaliert werden.

Zusätzlich soll die Skalierung zeitbasiert optimiert werden, um auf Spitzenbelastungen vorbereitet zu sein.

**Zuweisung von Bausteinen zur Infrastruktur**

Die Zuweisung der Bausteine ist in der Abbildung *Referenz Abbildung* visualisiert.

plantuml::structurizr_diagrams/generated/structurizr-deployment-singulaere-physioconnect.puml[format=svg]

[cols="1,1,2"]
|===
|Baustein|Zuweisung|Kommentar

|Therapie Planungs Service
|Managed Kubernetes Cluster
|Die Skalierung des __Therapie Planungs Service__ soll auf die Arbeitszeiten der Therapeuten Rücksicht nehmen.

|Ausführungsservice
|Managed Kubernetes Cluster
|Die Skalierung des __Ausführungsservice__ soll auf die typischen Ausführungszeiten der Therapie-Sessions (Morgen, Feierabend, Abend) Rücksicht nehmen.

|Server Side Therapie Manager
|Managed Kubernetes Cluster
|-

|Übungskatalogwrapper
|Managed Kubernetes Cluster
|-

|Benutzerverwaltungswrapper
|Managed Kubernetes Cluster
|-

|Load Balancer
|Managed Kubernetes Cluster
|Je nach Hyperscaler kann es sein, dass ein Load Balancer ausserhalb des Clusters eingerichtet werden muss.

|Therapie Planungs Datenbank
|Storage Service
|Zu diesem Zeitpunkt ist noch nicht entschieden, ob es sich bei dieser Datenbank um eine relationale oder Dokumentdatenbank handeln wird.

|Ausführungs Datenbank
|Storage Service
|Dokumentdatenbank. Es soll ein Service gewählt werden, welcher speziell für dieses Datenbankmodell ausgelegt ist. Da der spezifische Hyperscaler noch unbekannt ist, kann hier kein expliziter Service genannt werden.

|Übungskatalog
|Unbekanntes Hosting
|Der Übungskatalog befindet sich nicht im Systemkontext von Physio Connect und damit nicht im Scope dieser Dokumentation. +
Die Entscheidung, wo der Übungskatalog gehosted wird, ist für uns zu diesem Zeitpunkt irrelevant.

|Benutzerverwaltung
|Unbekanntes Hosting
|Die Benutzerverwaltung befindet sich nicht im Systemkontext von Physio Connect und damit nicht im Scope dieser Dokumentation. +
Die Entscheidung, wo die Benutzerverwaltung gehosted wird, ist für uns zu diesem Zeitpunkt irrelevant.

|===

==== Patienten Infrastruktur

Die Patienteninfrastruktur kann von uns nicht direkt beeinflusst werden. Gemäss des beschriebenen link:01_introduction_and_goals.adoc#section-introduction-and-goals[Architekturtreibers] *Mehrheitliche Verwendung des Smartphones* wird davon ausgegangen, dass der Grossteil aller Patienten ein Smartphone besitzt, welches mit der __mobilen Patientenapp__ kompatibel ist. Immer mehr Patienten besitzen __Fitness Tracker__, die Patientenapp funktioniert jedoch auch ohne Fitnesstracker.

In Ausnahmefällen können Patienten einen Fitnesstracker von ihrer jeweiligen Privatpraxis oder Rehabilitationsklinik erhalten. Dies hat jedoch keinen Einfluss auf unsere Infrastruktur.

==== SaaS Kunden Infrastruktur

Gemäss den *ADR-HST-11* wurde bestimmt, dass möglichst nur eine globale Instanz des Physio Connect-Systems produktiv eingesetzt werden sollte. Dies bedeutet, dass die Kunden __Physio Connect__ als https://www.ibm.com/topics/saas[System as a Service (SaaS)] beziehen.

Kunden können den __Therapien Manager__ mit den Geräten verwenden, welche sie bereits besitzen. Gemäss *ADR-FRO-10* und *ADR-FRO-13* werden die folgenden Platformen unterstützt:

* Web Browsers
** Chrome
** Firefox
** Edge
** Safari
* Mobile Browsers
** Chrome
** Safari
* Android (PWA)
* iOS (PWA)

=== Infrastruktur mit mehreren Physio Connect-Instanzen

**Motivation**

Gemäss *ADR-HST-10* muss die Möglichkeit offengehalten werden, dass Kunden eine eigene Instanz von Physio Connect in Betrieb haben. In diesem Kapitel werden die Konsequenzen dieser Eintscheidung hinsichtlich des Deployments aufgezeigt.

==== Zusammenspiel mit der Patientenapp

**Motivation**

Die Patientenapp muss die Möglichkeit besitzen, die Therapiedaten von mehreren Physio Connect-Instanzen zu erhalten. Da die Therapiedaten jedoch ganzheitlich von jeder Instanz eigens gehosted werden, können die Physio Connect-Instanzen aus der Sicht der Patientenapp komplett unabhängig bleiben. Wie die Patientenapp die Daten hinterlegt, dass die Requests an die korrekte Physio Connect-Instanz gerichtet werden, ist nicht im Scope dieser Dokumentation.

**Zuweisung von Bausteinen zur Infrastruktur**

plantuml::structurizr_diagrams/generated/structurizr-deployment-sicht-patientenapp.puml[format=svg]

Die folgenden Eigenschaften müssen beim Deployment und der Konfiguration eingehalten werden:

* Die Services einer __Physio Connect__-Instanz A dürfen nicht mit den Services einer anderen __Physio Connect__-Instanz B kommunizieren +
(andere Systeme wie z.B. die Benutzerverwaltung sind von dieser Regel ausgeschlossen)
* Therapiedaten einer Instanz A müssen getrennt von den Therapiedaten anderer Instanzen persistiert werden, vorzüglich in einer eigenen Datenbank pro Instanz 
* Ausführungsdaten einer Instanz A müssen getrennt von den Ausführungsdaten anderer Instanzen persistiert werden, vorzüglich in einer eigenen Datenbank pro Instanz

Da wir keinen direkten Einfluss auf die Infrastruktur eines Kunden besitzen, wurden hierbei Annahmen getroffen. Die Kunden sollen beim Aufbau der Infrastruktur unterstützt werden, sodass Sicherheits- und Performance-Qualitätsattribute eingehalten werden können. Schlussendlich sind jedoch die Kunden für die Angemessenheit der Infrastruktur verantwortlich.

==== Verwendung des Therapien Managers

**Motivation**

Der __Therapien Manager__ muss mit der Version der darunterliegenden __Physio Connect__-Instanz übereinstimmen. Aus diesem Grund müssen alle Deployments von __Physio Connect__ einen eigenen __Server Side Therapie Manager__ besitzen, welcher für die Auslieferung des versionskonformen __Therapien Manager__ (SPA / PWA) an die Endbenutzergeräte zuständig ist.

**Qualitäts- und Performance-Eigenschaften**

Alle deployten __Server Side Therapie Manager__-Instanzen werden eine dedizierte URL benötigen. Dies führt dazu, dass Therapeuten eines Spitals mit eigens gehosteter __Physio Connect__-Instanz eine andere URL verwenden als unsere SaaS Kunden. Da die Therapeuten immer mit der gleichen __Physio Connect__-Instanz arbeiten, hat dies keinen Einfluss auf die Usability. Falls Patienten an mehreren Therapien teilnehmen, kann es jedoch sein, dass sie unterschiedliche __Therapien Manager__ verwenden müssen. Die Verwendung von unterschiedlichen URLs und unterschiedlich hinterlegten Daten verschlechtern die User Experience (UX) für Patienten.

**Zuweisung von Bausteinen zur Infrastruktur**

Zu diesem Zeitpunkt ist es noch nicht bekannt, ob alle __Physio Connect__-Instanzen eine globale Instanz der Benutzerverwaltung und des Übungskatalogs verwenden.

[.landscape]
<<<

plantuml::structurizr_diagrams/generated/structurizr-deployment-sicht-therapiemanager.puml[format=svg]

[.portrait]
<<<

==== Gesamtübersicht

Das folgende Diagramm repräsentiert die Gesamtübersicht eines Deployments mit zwei __Physio Connect__-Instanzen. Das Diagramm wird zum Zwecke der Vollständigkeit aufgeführt, sollte jedoch nur bedingt zur Kommunikation verwendet werden, da es zu überladen ist.

[.landscape]
<<<

plantuml::structurizr_diagrams/generated/structurizr-deployment-mehrere-physioconnect-komplett.puml[format=svg]


[.portrait]
<<<