[[section-design-decisions]]
== Architekturentscheidungen

In diesem Kapitel werden alle relevanten Architekturentscheidungen in Form von __Architectural Decision Records (ADRs)__ gemäss https://www.iso.org/standard/50508.html[ISO 42010] definiert. +
Die Entscheidungen sind jeweils thematisch gruppiert, damit sie besser auffindbar sind.

Das Format der Entscheidungen basiert auf dem folgenden Template:

[cols="2,6"]
|===
|**ID**|ADR-[Kategorie]-[Nummer]
|**Anliegen (Concern)**|Anliegen, welches die Grundlage für die Entscheidung darstellt. Formuliert als Fragestellung.
|**Kontext**|Beschreibung der Ausgangslage, um die Relevanz des Anliegens hervorzuheben.
|**Alternativen**
a|
Auflistung der möglichen Alternativen, inkl. deren Vor- und Nachteile.

* [Option 1]
** Beschreibung
** Vorteile
** Nachteile
* [Option 2]
** ...
* [Option 3]
** ...

|**Entscheidung**|Resultat der Entscheidungsfindung bzw. welche der Alternativen eingesetzt wird.
|**Begründung**
a|

* Weshalb wurde Alternative x ausgewählt?
* Beschreibung der eventuellen Konsequenzen (positiv oder negativ), welche beim Einsatz der Alternative x speziell zu beachten sind

|**Follow-up Entscheidungen**|Auflistung der benötigten Entscheidungen, welche aus dieser Entscheidung resultieren und zusätzlich getroffen werden müssen.
|===

=== Security

TBD
