[[section-quality-requirements]]
== Qualitätsanforderungen

In diesem Kapitel werden die nicht-funktionalen bzw. Qualitätsanforderungen an PhysioConnect anhand der Definition expliziter Szenarien konkretisiert. Die wichtigsten Szenarien werden in Form eines Quality Trees gemäss ATAM (Architecture Tradeoff Analysis Method) ihrer Relevanz entsprechend priorisiert / gewichtet.

Die primären Qualitätsziele von PhysioConnect sind im Kapitel link:01_introduction_and_goals.adoc#section-quality-goals[Qualitätsziele] vorzufinden.

=== Qualitätsszenarien

Gemäss den primären link:01_introduction_and_goals.adoc#section-quality-goals[Qualitätszielen] werden die aus Sicht der Stakeholder erwarteten Qualitätsattribute der Systemarchitektur in Form von messbaren Szenarien nachfolgend erläutert.

==== Interoperability
Szenarien, welche sich auf Qualitätsziel QG-1 (Interoperability) beziehen.

[cols="2,6"]
|===
|**ID**|SZ-IOP-1
|**Quelle des Stimulus**|-
|**Stimulus**|-
|**Umgebung**|-
|**Artefakt / System**|-
|**Antwort / Verhalten**|-
|**Metrik für Erfüllungsgrad**|-
|===

==== Confidentiality
Szenarien, welche sich auf Qualitätsziel QG-2 (Confidentiality) beziehen.

[cols="2,6"]
|===
|**ID**|SZ-CNF-1
|**Quelle des Stimulus**|-
|**Stimulus**|-
|**Umgebung**|-
|**Artefakt / System**|-
|**Antwort / Verhalten**|-
|**Metrik für Erfüllungsgrad**|-
|===

==== Modifiability
Szenarien, welche sich auf Qualitätsziel QG-3 (Modifiability) beziehen.

[cols="2,6"]
|===
|**ID**|SZ-MOD-1
|**Quelle des Stimulus**|-
|**Stimulus**|-
|**Umgebung**|-
|**Artefakt / System**|-
|**Antwort / Verhalten**|-
|**Metrik für Erfüllungsgrad**|-
|===

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****

=== Quality Tree

Die nachfolgend ersichtliche Darstellung repräsentiert eine Priorisierung / Gewichtung der oberhalb definierten Szenarien in Form eines Quality Trees, um eine zukünftige Evaluation der Systemarchitektur gemäss ATAM (Architecture Tradeoff Analysis Method) zu ermöglichen.

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****
