@startuml
title Systemlandschaft von Physio Connect

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam person<<Administratorin>> {
  BackgroundColor #444444
  FontColor #ffffff
  BorderColor #2f2f2f
}
skinparam rectangle<<Benutzerverwaltung>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<FitnessTracker>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<MobilePatientenapp>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam person<<Patientin>> {
  BackgroundColor #444444
  FontColor #ffffff
  BorderColor #2f2f2f
}
skinparam rectangle<<PhysioConnect>> {
  BackgroundColor #000000
  FontColor #ffffff
  BorderColor #000000
}
skinparam person<<Therapeutin>> {
  BackgroundColor #444444
  FontColor #ffffff
  BorderColor #2f2f2f
}
skinparam rectangle<<Übungskatalog>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}

package "Unternehmungsgrenze" <<enterprise>> {
  skinparam PackageBorderColor<<enterprise>> #444444
  skinparam PackageFontColor<<enterprise>> #444444

  rectangle "==Physio Connect\n<size:10>[Software System]</size>\n\nBietet eine Webapplikation zur Verwaltung von Therapie-Planungsdaten und eine Schnittstelle zum Empfangen und Persistieren von Ausführungsdaten an." <<PhysioConnect>> as PhysioConnect
  rectangle "==Mobile Patientenapp\n<size:10>[Software System]</size>" <<MobilePatientenapp>> as MobilePatientenapp
  rectangle "==Übungskatalog\n<size:10>[Software System]</size>" <<Übungskatalog>> as Übungskatalog
  rectangle "==Benutzerverwaltung\n<size:10>[Software System]</size>\n\nAuthentifizierung und Autorisierung" <<Benutzerverwaltung>> as Benutzerverwaltung
}

package "Patient*in\n[Group]" <<group:Patient*in>> {
  skinparam PackageBorderColor<<group:Patient*in>> #589fd8
  skinparam PackageFontColor<<group:Patient*in>> #589fd8

  person "==Patient*in\n<size:10>[Person]</size>\n\nPatient*in der jeweiligen Physio Organisation" <<Patientin>> as Patientin
  rectangle "==Fitness Tracker\n<size:10>[Software System]</size>" <<FitnessTracker>> as FitnessTracker
}

package "Physiounternehmung\n[Group]" <<group:Physiounternehmung>> {
  skinparam PackageBorderColor<<group:Physiounternehmung>> #b6862e
  skinparam PackageFontColor<<group:Physiounternehmung>> #b6862e

  person "==Therapeut*in\n<size:10>[Person]</size>\n\nPerson, welche Physiotherapien leitet" <<Therapeutin>> as Therapeutin
  person "==Administrator*in\n<size:10>[Person]</size>" <<Administratorin>> as Administratorin
}


PhysioConnect .[#707070,thickness=2].> Patientin : "<color:#707070>Physio Connect sendet Einladung für Therapie"
Administratorin .[#707070,thickness=2].> PhysioConnect : "<color:#707070>Administriert Personal und Übungen"
Therapeutin .[#707070,thickness=2].> PhysioConnect : "<color:#707070>Plant Therapien direkt,\nSendet Therapieeinladungen,\nErstellt eigene Übungen"
Patientin .[#707070,thickness=2].> MobilePatientenapp : "<color:#707070>Registriert sich,\nNimmt Therapieeinladungen an,\nBenutzt App für selbstständige Ausführung von Therapien"
Patientin .[#707070,thickness=2].> FitnessTracker : "<color:#707070>Besitzt"d
Patientin .[#707070,thickness=2].> PhysioConnect : "<color:#707070>Patient*in verwaltet selbsterstellte Therapien\n\n\n"
MobilePatientenapp .[#707070,thickness=2].> FitnessTracker : "<color:#707070>Mobile App verbindet sich mit Fitness Tracker\n\n"
FitnessTracker .[#707070,thickness=2].> MobilePatientenapp : "<color:#707070>Fitnesstracker sendet Messdaten"
MobilePatientenapp .[#707070,thickness=2].> PhysioConnect : "<color:#707070>Sendet Session-Updates mit Messdaten,\nRegistrierung neue Benutzer*innen,\nAuthentifiziert Benutzer*innen"
PhysioConnect .[#707070,thickness=2].> MobilePatientenapp : "<color:#707070>Sendet Therapien, Sessions und Übungen"
PhysioConnect .[#707070,thickness=2].> Übungskatalog : "<color:#707070>Importiert Übungen"
PhysioConnect .[#707070,thickness=2].> Benutzerverwaltung : "<color:#707070>Authentifiziert und autorisiert Benutzer*innen,\nErstellt neue Benutzer*innen"
@enduml