@startuml Therapie Lifecicle
title Zuweisungsstatus Patient*in

State Gesund
State Hospitalisiert #Orange
State InAmbulanterBehandlung #LightGreen
State InRehabilitation #LightBlue

[*] --> Gesund

Gesund ---->  Hospitalisiert : --[ Zugewiesen via Hausarzt/Hausärztin oder Facharzt/Fachärztin\nvia Notfall
Gesund ---->  InRehabilitation : --[ Zugewiesen via Hausarzt/Hausärztin oder Facharzt/Fachärztin
Gesund ---->  InAmbulanterBehandlung : --[ Verordnet

Hospitalisiert --[#Red]--> InRehabilitation : --[ Umgeteilt in Reha
Hospitalisiert --[#Red]--> InAmbulanterBehandlung : --[ Entlassen mit Verordnung
Hospitalisiert --[#Red]--> SelbstständigeBehandlung : --[ Entlassen ohne Verordnung

InRehabilitation --[#Blue]-> InAmbulanterBehandlung : --[ Entlassen mit Verordnung
InRehabilitation --[#Blue]--> Hospitalisiert : --[ Lage verschlechtert
InRehabilitation --[#Blue]--> SelbstständigeBehandlung : --[ Entlassen ohne Verordnung

InAmbulanterBehandlung --[#Green]--> Hospitalisiert : --[ Lage verschlechtert
InAmbulanterBehandlung --[#Green]--> SelbstständigeBehandlung : --[ Verordnung abgeschlossen

SelbstständigeBehandlung --> [*]

@enduml