@startuml Therapie Lifecicle
title Therapie Übung Lebenszyklus

State Erstellt
State NachtraeglichErfasst
State Uebersprungen
State Gestartet
State Unterbrochen
State Abgebrochen
State Abgeschlossen

[*] --> Erstellt

Erstellt -----> NachtraeglichErfasst
Erstellt -----> Uebersprungen
Erstellt --> Gestartet
Gestartet --> Unterbrochen
Gestartet --> Abgebrochen
Gestartet ---> Abgeschlossen
Unterbrochen --> Gestartet
Unterbrochen --> Abgebrochen 
Abgebrochen --> [*]
NachtraeglichErfasst --> [*]
Uebersprungen --> [*]
Abgeschlossen --> [*]

 @enduml