name: build
run-name: Build Documentation
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate diagrams and documentation
        run: docker-compose up

      - name: Check for generated files
        shell: pwsh
        run: |
          Write-Host $PWD

          dir "$PWD/physio_connect_c4/generated"
          dir "$PWD/arc42_documentation"

          $diagramsExist = Test-Path -Path "$PWD/physio_connect_c4/generated/*.puml" -PathType leaf
          $pdfExists = Test-Path -Path "$PWD/arc42_documentation/*.pdf*" -PathType leaf

          Write-Host "Diagrams found: $diagramsExist"
          Write-Host "Documentation (PDF) found: $pdfExists"

          if (!$diagramsExist -or !$pdfExists) {
            Exit 1
          }
