name: build
run-name: Build Documentation
on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate diagrams and documentation
        run: docker-compose up

      - name: Check for generated files
        shell: pwsh
        run: |
          Write-Host $PWD

          Get-ChildItem -Path "$PWD/arc42_documentation"
          Get-ChildItem -Path "$PWD/arc42_documentation/structurizr_diagrams/generated"
          Get-ChildItem -Path "$PWD/arc42_documentation/domain_model"

          $structurizrDiagramsExist = Test-Path -Path "$PWD/arc42_documentation/structurizr_diagrams/generated/*.puml" -PathType leaf
          $domainModelDiagramsExist = Test-Path -Path "$PWD/arc42_documentation/domain_model/domain_*.puml" -PathType leaf
          $pdfExists = Test-Path -Path "$PWD/arc42_documentation/physio_connect.pdf" -PathType leaf

          Write-Host "C4 diagrams found: $structurizrDiagramsExist"
          Write-Host "Domain model diagrams found: $domainModelDiagramsExist"
          Write-Host "Documentation (PDF) found: $pdfExists"

          if (!$structurizrDiagramsExist -or !$domainModelDiagramsExist -or !$pdfExists) {
            Exit 1
          }
      
      # only upload artifact if it is part of a new release (tag)
      - uses: actions/upload-artifact@v3
        with:
          name: documentation_pdf
          path: "$PWD/arc42_documentation/physio_connect.pdf"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
