name: create-release
run-name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  call-build:
    uses: markuskaufmann/CAS_SA_Transfer/.github/workflows/build.yml@${{ github.ref_name }}

  create-release:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download documentation artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: documentation_pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}

      - name: Upload artifact as Release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "$PWD/physio_connect.pdf"
          asset_name: PhysioConnect_${{ github.ref_name }}.pdf
          asset_content_type: application/pdf
